##  50 grms see upload

In [1]:
import random
import re
import datetime
import pandas as pd
import numpy as np
import requests
import io
import json
import random
from random import randint
from base64 import b64encode, b64decode
from django.contrib.auth.hashers import make_password
from django.core.files.base import ContentFile
from decimal import Decimal
try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO
    from io import BytesIO

# #  100gr   
# google_sheet_url = 'https://docs.google.com/spreadsheets/d/1QxCyP3uVTvUOG7IuhOCx0V-Qp07BVoIhsHBrj8NxkKU/export?format=csv'

# 50gr
google_sheet_url = 'https://docs.google.com/spreadsheets/d/1w1oCUQrlk8ODccERVI02qDndEfcWYkMOkYdLUPPCapY/export?format=csv'

r = requests.get(google_sheet_url)
data = r.content
df = pd.read_csv(BytesIO(data))
local_index = []
df = df.fillna(0)
# df = df.head(2)
df

,SL NO,R. No,Distribution/Return,Agents New/Old,Date,Agent Name,Unique Code,Supervisor Name,Moblie Number,50 Grm Pkt,0.5 Acre
0,1,3951,Distribution,Old,25-02-2022,Gopala H,A,shivakumar0,7406990508,100,50.0
1,2,3952,Distribution,Old,25-02-2022,S Muruga Sargur,C,siddapa,9449203315,100,50.0
2,3,3953,Distribution,Old,25-02-2022,M Parameshwaran,G,prasad,9738880982,40,20.0
3,4,3954,Distribution,Old,25-02-2022,M Parameshwaran,D,siddapa,9738080983,200,100.0
4,5,3955,Distribution,Old,25-02-2022,M Parameshwaran,F,srinivasa,9738080984,60,30.0
...,...,...,...,...,...,...,...,...,...,...,...
85,119,962,Distribution,Old,31-03-2022,Bangaranayak,B,naveen,9980310639,12,6.0
86,123,964,Distribution,Old,07-04-2022,C Mahesh Nanjangud,B,prasad,8548088094,3,1.5
87,129,968,Distribution,Old,09-04-2022,Ravi M S,F,siddapa,9379134626,13,6.5
88,133,969,Distribution,New,11-04-2022,Basavanna M,A,prasad,9900914192,16,8.0
89,137,972,Distribution,New,12-04-2022,Shivumurthy,J,naveen,9740126674,6,3.0

In [2]:
ext = []
for index, row in df.iterrows():
    date_string = row['Date']
    date = pd.to_datetime(date_string).date()
    if ComboIssueRequest.objects.filter(issue_rised_date=date, quantity_in_numbers=row['50 Grm Pkt']).exists():
        ext.append(row['Date'])
print(len(ext))

90

/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-02-25 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-02-26 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-02-28 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-02-03 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-05-03 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-07-03 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-08-03 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-09-03 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-11-03 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-12-03 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-03-16 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-03-18 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-03-31 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-07-04 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-09-04 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-11-04 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-12-04 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "

##  new seed data

In [ ]:
def generate_request_code(input_combo_id):
    code_bank_obj = ComboIssueRequestCodeBank.objects.filter(input_combo_id=input_combo_id)[0]
    last_digit_code = code_bank_obj.last_digit
    new_code = last_digit_code + 1
    value = str(code_bank_obj.input_combo.name) + str(new_code).zfill(3)
    code_bank_obj.last_digit = new_code
    code_bank_obj.save()
    return value

import random

aggri_officer_ids= [82, 99]

r =  random.choice(aggri_officer_ids)
r

In [6]:
import random
import re
import datetime
import pandas as pd
import numpy as np
import requests
import io
import json
import random
from random import randint
from base64 import b64encode, b64decode
from django.contrib.auth.hashers import make_password
from django.core.files.base import ContentFile
from decimal import Decimal
try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO
    from io import BytesIO
# google_sheet_url = 'https://docs.google.com/spreadsheets/d/1QxCyP3uVTvUOG7IuhOCx0V-Qp07BVoIhsHBrj8NxkKU/export?format=csv'
google_sheet_url = 'https://docs.google.com/spreadsheets/d/1Y3sNEAJUqCj8VUSye1qnfBBtsHvDJcaC1avMLRuv2Cg/export?format=csv'

r = requests.get(google_sheet_url)
data = r.content
new_df = pd.read_csv(BytesIO(data))
local_index = []
new_df = new_df.fillna(0)
# df = df.head(2)
new_df

,no,SL NO,Distribution/Return,Agents New/Old,Date,Agent Name,Unique Code,Supervisor Name,Moblie Number,50 Grm Pkt,0.5 Acre
0,1,1,Distribution,Old,25-02-2022,Gopala H,A,shivakumar0,7406990508,100,50.0
1,2,2,Distribution,Old,25-02-2022,S Muruga Sargur,C,siddapa,9449203315,100,50.0
2,3,3,Distribution,Old,25-02-2022,M Parameshwaran Nanjangud,G,prasad,9738880982,40,20.0
3,4,4,Distribution,Old,25-02-2022,M Parameshwaran Sargur,D,siddapa,9738080983,200,100.0
4,5,5,Distribution,Old,25-02-2022,M Parameshwaran H D Kote,F,srinivasa,9738080984,60,30.0
...,...,...,...,...,...,...,...,...,...,...,...
137,138,164,Distribution,Old,27-04-2022,Mahesh K,A,harish,9900348416,0,0.0
138,139,165,Distribution,Old,02-05-2022,R Ravi,H,naveen,6360227141,4,2.0
139,140,167,Distribution,Old,02-05-2022,Shivumurthy,J,naveen,9740126674,4,2.0
140,141,169,Distribution,Old,02-05-2022,Basappa K,A,madappa,9632034111,10,5.0
141,142,171,Distribution,Old,12-05-2022,B M Veerabhadrappa H D Kote,A,srinivasa,8887999456,10,5.0

In [7]:
not_ext = []
for index, row in new_df.iterrows():
    date_string = row['Date']
    date = pd.to_datetime(date_string).date()
    if ComboIssueRequest.objects.filter(issue_rised_date=date, quantity_in_numbers=row['50 Grm Pkt']).exists():
        not_ext.append(row['Date'])
print(len(not_ext))

101

/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-02-25 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-02-26 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-02-28 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-02-03 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-05-03 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-07-03 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-08-03 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-09-03 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-10-03 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-11-03 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-12-03 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-03-14 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-03-15 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-03-16 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-03-18 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-03-22 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-03-23 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-03-24 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-03-26 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-03-29 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-03-31 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-05-04 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-07-04 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-09-04 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-11-04 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-12-04 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-04-14 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-04-15 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-04-18 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-04-19 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-04-21 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-04-23 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-04-26 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-04-27 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-02-05 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/home/steve/Software/virtualenv/ccgb/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1390: RuntimeWarning: DateTimeField ComboIssueRequest.issue_rised_date received a naive datetime (2022-12-05 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "

In [2]:
import pandas as pd
df = pd.DataFrame(ComboIssueRequest.objects.filter(season_id=4, input_combo_id=9).values())
df

,id,season_id,request_code,input_combo_id,quantity_in_numbers,quantity_for_area,expected_date,issue_rised_date,max_status_id,max_status_date,...,agri_officer_status_id,agri_officer_status_date,gm_id,gm_status_id,gm_status_date,dispatched_by_id,dispatch_status_id,dispatch_date,time_modified,time_created
0,960,4,Half Acre Seed Pkt169,9,100,50.00,2022-02-25 00:00:00+00:00,2022-02-25 00:00:00+00:00,6,2022-02-25 00:00:00+00:00,...,1,2022-02-25 00:00:00+00:00,78,1,2022-02-25 00:00:00+00:00,None,None,None,2022-04-26 04:07:26.932457+00:00,2022-04-26 04:07:26.932474+00:00
1,961,4,Half Acre Seed Pkt170,9,100,50.00,2022-02-25 00:00:00+00:00,2022-02-25 00:00:00+00:00,6,2022-02-25 00:00:00+00:00,...,1,2022-02-25 00:00:00+00:00,78,1,2022-02-25 00:00:00+00:00,None,None,None,2022-04-26 04:07:26.963470+00:00,2022-04-26 04:07:26.963483+00:00
2,962,4,Half Acre Seed Pkt171,9,40,20.00,2022-02-25 00:00:00+00:00,2022-02-25 00:00:00+00:00,6,2022-02-25 00:00:00+00:00,...,1,2022-02-25 00:00:00+00:00,78,1,2022-02-25 00:00:00+00:00,None,None,None,2022-04-26 04:07:26.993618+00:00,2022-04-26 04:07:26.993631+00:00
3,963,4,Half Acre Seed Pkt172,9,200,100.00,2022-02-25 00:00:00+00:00,2022-02-25 00:00:00+00:00,6,2022-02-25 00:00:00+00:00,...,1,2022-02-25 00:00:00+00:00,78,1,2022-02-25 00:00:00+00:00,None,None,None,2022-04-26 04:07:27.022949+00:00,2022-04-26 04:07:27.022966+00:00
4,964,4,Half Acre Seed Pkt173,9,60,30.00,2022-02-25 00:00:00+00:00,2022-02-25 00:00:00+00:00,6,2022-02-25 00:00:00+00:00,...,1,2022-02-25 00:00:00+00:00,78,1,2022-02-25 00:00:00+00:00,None,None,None,2022-04-26 04:07:27.045934+00:00,2022-04-26 04:07:27.045945+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,1045,4,Half Acre Seed Pkt254,9,12,6.00,2022-03-31 00:00:00+00:00,2022-03-31 00:00:00+00:00,6,2022-03-31 00:00:00+00:00,...,1,2022-03-31 00:00:00+00:00,78,1,2022-03-31 00:00:00+00:00,None,None,None,2022-04-26 04:07:28.955350+00:00,2022-04-26 04:07:28.955361+00:00
86,1046,4,Half Acre Seed Pkt255,9,3,1.50,2022-07-04 00:00:00+00:00,2022-07-04 00:00:00+00:00,6,2022-07-04 00:00:00+00:00,...,1,2022-07-04 00:00:00+00:00,78,1,2022-07-04 00:00:00+00:00,None,None,None,2022-04-26 04:07:28.977426+00:00,2022-04-26 04:07:28.977436+00:00
87,1047,4,Half Acre Seed Pkt256,9,13,6.50,2022-09-04 00:00:00+00:00,2022-09-04 00:00:00+00:00,6,2022-09-04 00:00:00+00:00,...,1,2022-09-04 00:00:00+00:00,78,1,2022-09-04 00:00:00+00:00,None,None,None,2022-04-26 04:07:29.004834+00:00,2022-04-26 04:07:29.004844+00:00
88,1048,4,Half Acre Seed Pkt257,9,16,8.00,2022-11-04 00:00:00+00:00,2022-11-04 00:00:00+00:00,6,2022-11-04 00:00:00+00:00,...,1,2022-11-04 00:00:00+00:00,78,1,2022-11-04 00:00:00+00:00,None,None,None,2022-04-26 04:07:29.029617+00:00,2022-04-26 04:07:29.029629+00:00
89,1049,4,Half Acre Seed Pkt258,9,6,3.00,2022-12-04 00:00:00+00:00,2022-12-04 00:00:00+00:00,6,2022-12-04 00:00:00+00:00,...,1,2022-12-04 00:00:00+00:00,78,1,2022-12-04 00:00:00+00:00,None,None,None,2022-04-26 04:07:29.054510+00:00,2022-04-26 04:07:29.054528+00:00