In [41]:
import re
import datetime
import pandas as pd
import numpy as np
import requests
import io
import json
import random
from random import randint
from base64 import b64encode, b64decode
from django.contrib.auth.hashers import make_password
from django.core.files.base import ContentFile
from decimal import Decimal
try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO
    from io import BytesIO
google_sheet_url = 'https://docs.google.com/spreadsheets/d/1xkzCIEflGMhi8ymUBdQpZPZPfjT4ItPSzKeOsUNW2H4/export?format=csv'

r = requests.get(google_sheet_url)
data = r.content
df = pd.read_csv(BytesIO(data))
local_index = []
df = df.fillna(0)
df.head(1)

,Sl. No,Rl. No,Distribution/Return,Date,Agent Name,Agent Code,Village Name,Supervisor Name,Cluster Name,From 100,To 100,No of Packets 100,Acre 100
0,1,1,Distribution,25-02-2021,M Parameshwaran,AS055,Gundlupet,siddapa,Sargur,1,85,85,85

In [44]:
ComboIssueRequest.objects.filter(input_combo_id__in=[8,9]).delete()

(0, {})

In [ ]:
for index, row in df.iterrows():
    aggri_officer_ids= [82, 99]
    village_name = row['Village Name']
   
    date_string = row['Date']
    date = pd.to_datetime(date_string).date()
   
    supervisor_id = User.objects.get(username=row['Supervisor Name']).id
    superior_id = senior_supervisor_id(supervisor_id)
   
    input_combo_obj = InputCombo.objects.get(id=8)
   
    combo_request_obj = ComboIssueRequest(request_code=generate_request_code(8),
                                        season_id=3,
                                        input_combo_id=8,
                                        quantity_in_numbers=row['No of Packets 100'],
                                        quantity_for_area=row['Acre 100'],
                                        expected_date=date,
                                        issue_rised_date=date,
                                        max_status_id=2,
                                        max_status_date=date,
                                        supervisor_id=User.objects.get(username=row['Supervisor Name']).id,
                                        senior_supervisor_id=superior_id,
                                        senior_supervisor_status_id=2,
                                        senior_supervisor_status_date=date,
                                        assitant_manager_id=79,
                                        assitant_manager_status_id=2,
                                        assitant_manager_status_date=date,
                                        agri_officer_id=aggri_officer_ids[random_index],
                                        agri_officer_status_id = 2,
                                        agri_officer_status_date=date,
                                        gm_id = 78,
                                        gm_status_id =2,
                                        gm_status_date=date)
    combo_request_obj.save()

In [9]:
lists = [[2,3], [3,4]]
d = []
for a in lists:
    dicts = []
    for b in a:
        b = b + 10
        dicts.append(b)
    d.append(dicts)
print(d)

[[12, 13], [13, 14]]

In [2]:
input_list = [139]
import pandas as pd
main_df = pd.DataFrame(list(InputSubStoreInventory.objects.filter(input_store_inventory__input_packet_inventory__input_combo__id__in=[8,9]).order_by('id').values()))
main_df.head(4)
main_df

,id,season_id,input_store_inventory_id,sub_storage_id,section,sub_section,date_of_receipt,quantity_at_receipt,quantity_now,quantity_now_time,unit_id,label_range_start,label_range_end,created_by_id,modified_by_id,time_modified,time_created
0,43,3,54,1,,,2021-05-03,138,138,2021-05-03 12:52:46.585091+00:00,4,S21F11M1,S21F1138M1,116,116,2021-05-03 12:52:47.453997+00:00,2021-05-03 12:52:46.586044+00:00
1,44,3,55,1,,,2021-05-03,379,379,2021-05-03 12:52:47.460505+00:00,4,S21F1139M1,S21F1517M1,116,116,2021-05-03 12:52:49.164860+00:00,2021-05-03 12:52:47.460881+00:00
2,45,3,56,1,,,2021-05-03,646,646,2021-05-03 12:52:49.170140+00:00,4,S21F1518M1,S21F11163M1,116,116,2021-05-03 12:52:52.103139+00:00,2021-05-03 12:52:49.170529+00:00
3,46,3,57,1,,,2021-05-03,909,909,2021-05-03 12:52:52.108378+00:00,4,S21F11164M1,S21F12072M1,116,116,2021-05-03 12:52:56.411343+00:00,2021-05-03 12:52:52.108996+00:00
4,47,3,58,1,,,2021-05-03,391,391,2021-05-03 12:52:56.418658+00:00,4,S21F12073M1,S21F12463M1,116,116,2021-05-03 12:52:58.440413+00:00,2021-05-03 12:52:56.419116+00:00
5,48,3,59,1,,,2021-05-03,131,131,2021-05-03 12:52:58.447739+00:00,4,S21F12464M1,S21F12594M1,116,116,2021-05-03 12:52:59.118930+00:00,2021-05-03 12:52:58.448069+00:00
6,49,3,60,1,,,2021-05-03,390,390,2021-05-03 12:52:59.124019+00:00,4,S21F12595M1,S21F12984M1,116,116,2021-05-03 12:53:01.216160+00:00,2021-05-03 12:52:59.124269+00:00
7,50,3,61,1,,,2021-05-03,251,251,2021-05-03 12:53:01.221107+00:00,4,S21F12985M1,S21F13235M1,116,116,2021-05-03 12:53:02.695067+00:00,2021-05-03 12:53:01.221359+00:00
8,51,3,62,1,,,2021-05-03,127,127,2021-05-03 12:53:02.700340+00:00,4,S21F13236M1,S21F13362M1,116,116,2021-05-03 12:53:03.605304+00:00,2021-05-03 12:53:02.700684+00:00
9,52,3,63,1,,,2021-05-03,233,233,2021-05-03 12:53:03.614386+00:00,4,CCGB33631ST KIT,CCGB35951ST KIT,116,116,2021-05-03 12:53:05.029735+00:00,2021-05-03 12:53:03.614793+00:00

In [4]:
input_dict = []

for item in input_list:
    main_df = pd.DataFrame(list(InputSubStoreInventory.objects.filter(input_store_inventory__input_packet_inventory__input_combo__id__in=[8,9]).order_by('id').values()))
    print(item)
    for index, row in main_df.iterrows():
        if item < row['quantity_now'] or item == row['quantity_now']:
            temp_dict = {}
            temp_dict['id'] = [row.id] 
            temp_dict['entered_qty'] = item
            input_dict.append(temp_dict)
            break;
        else:
            temp_dict = {}
            temp_dict['id'] = [row.id] 
            temp_dict['entered_qty'] = row['quantity_now']
            input_dict.append(temp_dict)
            item = item - row['quantity_now']
input_dict

139

[{'id': [43], 'entered_qty': 138}, {'id': [44], 'entered_qty': 1}]

In [42]:
for index, row in df.iterrows():
    if not User.objects.filter(username=row['Supervisor Name']).exists():
        print(row['Supervisor Name'])