In [5]:
import pandas as pd
forest_office_obj = ForestOffice.objects.filter()
forest_official_obj = ForestOfficial.objects.all()

forest_value_list = list(forest_office_obj.values_list('id', 'forest__name', 'village', 'street', 'pincode', 'taluk', 'block', 'district', 'forestofficecropmap__crop_cv__name', 'image'))                                                                                                       
forest_value_column = ['forest_office_id', 'forest_name', 'village', 'street', 'pincode', 'taluk', 'block', 'district', 'crop', 'image']
forest_df = pd.DataFrame(forest_value_list, columns=forest_value_column)

# industry_df = industry_df.groupby(['industry_office_id', 'industry_name', 'village', 'street', 'pincode', 'taluk', 'block', 'district', 'image']).agg({'crop': 'unique'}).reset_index()

official_value_list = list(forest_official_obj.values_list('forest_office_id', 'user_profile__user__first_name', 'user_profile__user__last_name', 'user_profile__mobile', 'is_contact_person', 'user_profile__user__email'))
official_value_column = ['forest_office_id', 'first_nCasuarina  based agroforestryame', 'last_name', 'mobile', 'contact_person', 'email']
official_df = pd.DataFrame(official_value_list, columns=official_value_column)
official_df = official_df[official_df['contact_person']==True]
print('---------------------')
print(official_df.shape)
print(forest_df.shape)
final_df = pd.merge(forest_df, official_df, left_on='forest_office_id', right_on='forest_office_id', how='left')
final_df = final_df.fillna('')

---------------------
(2, 6)
(3, 10)

In [6]:
forest_df

,forest_office_id,forest_name,village,street,pincode,taluk,block,district,crop,image
0,6,comp 1,Arasamarathottam,Coimbatore,641016,Palladam,None,Coimbatore,None,
1,7,comp2,Arasamarathottam,Coimbatore,641016,Palladam,None,Coimbatore,None,
2,8,comp2,Coimbatore South,"10/12, Pechiamman street -2",641111,Coimbatore South,None,Coimbatore,None,

In [7]:
official_df

   forest_office_id first_name last_name  mobile  contact_person email
0                 6      ruban   bharath      32            True
1                 7      dfasf       asf     233            True

In [9]:
final_df = pd.merge(forest_df, official_df, left_on='forest_office_id', right_on='forest_office_id', how='left')
final_df

,forest_office_id,forest_name,village,street,pincode,taluk,block,district,crop,image,first_name,last_name,mobile,contact_person,email
0,6,comp 1,Arasamarathottam,Coimbatore,641016,Palladam,None,Coimbatore,None,,ruban,bharath,32.0,True,
1,7,comp2,Arasamarathottam,Coimbatore,641016,Palladam,None,Coimbatore,None,,dfasf,asf,233.0,True,
2,8,comp2,Coimbatore South,"10/12, Pechiamman street -2",641111,Coimbatore South,None,Coimbatore,None,,NaN,NaN,NaN,NaN,NaN

In [12]:
data_dict = {}
forest_official_obj = ForestOfficial.objects.get(user_profile__user_id=29)
forest_office_obj = forest_official_obj.forest_office
forest_id = forest_office_obj.forest_id
if forest_office_obj.is_head_office:
    data_dict['head_office'] = ForestOffice.objects.filter(id=forest_office_obj.id).values()[0]
    head_office_id = ForestOffice.objects.filter(id=forest_office_obj.id).values()[0]['id']
else:
    data_dict['head_office'] = ForestOffice.objects.filter(forest_id=forest_id, is_head_office=True).values()[0]
    head_office_id = ForestOffice.objects.filter(forest_id=forest_id, is_head_office=True).values()[0]['id']

#     branches
data_dict['branches'] = list(ForestOffice.objects.filter(forest_id=forest_id).exclude(id=head_office_id).values())
data_dict

{'head_office': {'id': 7,
  'name': 'head Office',
  'short_name': None,
  'forest_id': 6,
  'is_head_office': True,
  'state': 'TamilNadu',
  'district': 'Coimbatore',
  'block': None,
  'revenue_village': 'afdsa',
  'village': 'Arasamarathottam',
  'street': 'Coimbatore',
  'taluk': 'Palladam',
  'pincode': 641016,
  'latitude': None,
  'longitude': None,
  'image': ''},
 'branches': [{'id': 8,
   'name': 'secnd',
   'short_name': 'dfsa',
   'forest_id': 6,
   'is_head_office': False,
   'state': 'TamilNadu',
   'district': 'Coimbatore',
   'block': None,
   'revenue_village': 'sdfa',
   'village': 'Coimbatore South',
   'street': '10/12, Pechiamman street -2',
   'taluk': 'Coimbatore South',
   'pincode': 641111,
   'latitude': None,
   'longitude': None,
   'image': ''}]}

In [10]:
list(ForestOffice.objects.filter(forest_id=forest_id).exclude(forest_id=head_office_id).values())

[{'id': 7,
  'name': 'head Office',
  'short_name': None,
  'forest_id': 6,
  'is_head_office': True,
  'state': 'TamilNadu',
  'district': 'Coimbatore',
  'block': None,
  'revenue_village': 'afdsa',
  'village': 'Arasamarathottam',
  'street': 'Coimbatore',
  'taluk': 'Palladam',
  'pincode': 641016,
  'latitude': None,
  'longitude': None,
  'image': ''},
 {'id': 8,
  'name': 'secnd',
  'short_name': 'dfsa',
  'forest_id': 6,
  'is_head_office': False,
  'state': 'TamilNadu',
  'district': 'Coimbatore',
  'block': None,
  'revenue_village': 'sdfa',
  'village': 'Coimbatore South',
  'street': '10/12, Pechiamman street -2',
  'taluk': 'Coimbatore South',
  'pincode': 641111,
  'latitude': None,
  'longitude': None,
  'image': ''}]

In [1]:
from google_access import Create_Service
import pickle
import os
from google_auth_oauthlib.flow import Flow, InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from google.auth.transport.requests import Request
import requests

CLIENT_SECRET_FILE = 'google-client-data.json'
API_NAME = 'photoslibrary'
API_VERSION = 'v1'
SCOPES = ['https://www.googleapis.com/auth/photoslibrary','https://www.googleapis.com/auth/photoslibrary.sharing','https://www.googleapis.com/auth/photoslibrary.readonly']
service = Create_Service(CLIENT_SECRET_FILE, API_NAME, API_VERSION, SCOPES)
data_dict = service.albums().list().execute()

google-client-data.json-photoslibrary-v1-(['https://www.googleapis.com/auth/photoslibrary', 'https://www.googleapis.com/auth/photoslibrary.sharing', 'https://www.googleapis.com/auth/photoslibrary.readonly'],)
token_photoslibrary_v1.pickle
photoslibrary service created successfully

{'albums': [{'id': 'AKZrisBeHkVDeU6Ryo9-WLfWicL5MykIlvSeyDCmNMWe33CV6QWyic76pdcgYiJ-N-kJvHrSX8Y6',
   'title': 'சவுக்கு ',
   'productUrl': 'https://photos.google.com/lr/album/AKZrisBeHkVDeU6Ryo9-WLfWicL5MykIlvSeyDCmNMWe33CV6QWyic76pdcgYiJ-N-kJvHrSX8Y6',
   'mediaItemsCount': '5',
   'coverPhotoBaseUrl': 'https://lh3.googleusercontent.com/lr/AFBm1_Yhp-Vy6ncEdZ5fNERpkYQm6-pfg1j0GVksIOf94jr16NOsUWb6BhLSSoWMd9e7JWPtyOXgwdvaOjQVrgxddafyxPK8X4wk_-Ymm2quLjRRzhwNeze1lC65K5zY8TdrUv-jFVP3-Oz-8uTbvCALRz_IGvLYYNzlqkQ4cKWhu6XJHDmipS_3ik6HQrxL-jY8sZxnd6XuFsC33oth91G8Sew7akmT2LE2tu8psmSzWLN5_sgthaZJU3aagjsJwZRNOsPuhS2oSFhV0UxYLMph3lSwXlMvdTf2NvWPcM34CtDKQhiIS3SmvwZFuIENgFVaQ1KfAhytMkBwigZvWIFV8FV-XmnNoHAYLJAf7DLRhtKi29Q-whuee52XXqIgDpWCqnpcnNAADMFFbDwtl_qGuGvW810UkVb8mJ8ST9eqNapj4J3GTK6Kw__5ICc9kmW-_Tf7V_mGZRHlz8F-uHDaZd6Wo4bgr-D3e5fh2ScPpA-GuF_5TPpwrxKu3FMuw8tq8OJDogNbSUJNMxJxN4FGvChkt2x__VWO1jZiV8b76QWBdOx2IZzUxVJPAFfw0DZ-v286IdFzZ9R8_0KfH50qTbWR300G4FySn2sCw-CuzyeDF8n1QVjZ91Trmrns4dWWHiTtZ2uXA1yLaxOtjDgBwO4WT-f8AyiptqEYM2AKyk77aNmoN_dznMSrN_0Px0SeJsldtgfiefdlayFk0zXAnHAC1GQtlVbZyWfYUZ64uhhufYtwFn_8Y2qBmEm8vetL3KPlQOYBWaMa3ygoHmY6eMEaaMHW--lX__6R_vIePtu9Lyw51LkCvXC6Lxupr8euUXzCBboS_vgzCKuutw',
   'coverPhotoMediaItemId': 'AKZrisDbWDpwuSXbttJqqsFzbE-ow80NLFhSxa_FzoVCFSx2uvk9MffTS5w0lTbR_BmvFoT-ITDc5sk7JLctb55pBbOMox6KkQ'},
  {'id': 'AKZrisBeiTHHvmYOUF7N_ZWFsJQYIX6-YqVOaa5VXFON0asVMpc04aOsgziTyJX5G9tAxWO8M6g8',
   'title': 'Windbreak Tree Varieties of IFGTB  to protect Banana and other Crops',
   'productUrl': 'https://photos.google.com/lr/album/AKZrisBeiTHHvmYOUF7N_ZWFsJQYIX6-YqVOaa5VXFON0asVMpc04aOsgziTyJX5G9tAxWO8M6g8',
   'mediaItemsCount': '8',
   'coverPhotoBaseUrl': 'https://lh3.googleusercontent.com/lr/AFBm1_ZQB8N2lZrdeE8HFFuY6qoD__L4ZSnMGBsa_WO6q-07O9r3t6z-sVd3_ec_xc2h52tdvbkV3vZpRj4RZBjvP2-NHH5W8zxJ4_vq9i6xKF0o9lL0ZMOp7HPkQKiIy11lqSV11e0J1xe3-UduokjoH2XlI_3AZjtfTSxQPU6W6ogPe6cWRPqoOmCztKNjp-9EBl0PSdYqs8P30oKivOnoDvJT2mZoI8_P0O7lMq7StB4Wl8IwLHhHqA6ZUalmxHNM_4PIQZ8K_yLf9FZvRcYjj1KnFlX9uXr6j5Det-ei4YHq0dj-uEGBVdbXo2JN5yIOEMU4K3QGLXxrmw4Pt_6550QSMDJiLm2Xlm_N4DqrkM74NzIIkHLPirzTvAOk0W0QYABiDncOe-LvMTYMBqKfU8ro6Uk0cJmTpBJcBbgk5HdjOLM1drTFDRUR833pYewTuqYKglqyhmIpYKbs_9u6V7ESdEtefK_PsC_lxstKHxuL7Txgoa6mEJsS1QQ1UcZmnbySTtoiCUAhMWlZZRqm3Mf76lG-xEobFS3iWnxGpt1FJJK13-vKvhmNZzU2ShBPXNb2jbYCxApW97_HDkLtA3YnNzNsgoDxz9GNX9fQKUwtqFE686b1dxVNc9x9QHLD4xhLnSVjeHSsA9HvsuNg3M8SK6appc6iGADdeYo6nAg3sSUuZa0kUbWwDmXiiVi45gEhh-61AjZA_iZnPPEpAvX-9tjaKIF84z69EuXTlFi_-9ykmUcjQqnWFSx22n-w9fwe0vyNaQ2uCGuTG1CvHQQU0d7d-widyTwikf4uQOu3joj-yTlcLVjRECFynoFOVXe2G1FQIFxQEVlS9w',
   'coverPhotoMediaItemId': 'AKZrisAQ15r4Naq3zDdT3iHz6iyPhePEcrOWYuHgrda1mNW1iqiWs_gpVHRl_EumR6CAwNo0LRSxAjbZtUfz49Vnqzk4VDBBCw'},
  {'id': 'AKZrisDCXZTEeYUCTYiAaVYMWoEU0GnCAyiiJlhi7CqJSuBaBX9AARFY9aqtPEoOEahq-mrqUuks',
   'title': 'NEOLAMARCKIA CADAMBA (Roxb.) Miq – AN INDIGENOUS MULTIPURPOSE TREE',
   'productUrl': 'https://photos.google.com/lr/album/AKZrisDCXZTEeYUCTYiAaVYMWoEU0GnCAyiiJlhi7CqJSuBaBX9AARFY9aqtPEoOEahq-mrqUuks',
   'mediaItemsCount': '23',
   'coverPhotoBaseUrl': 'https://lh3.googleusercontent.com/lr/AFBm1_aPcicpbd6VRqr4pRUz_n4NmzdQbYorRaW2CutlGR_NPEzn6cAY3ma6Q9vnw5XfVE9kSXhZLMJwlJ-REUFEleoIGGFOTe4D7efHbVKI9__3xnO89_iT863R22mA7nncpUAbbz9x6UoNNjvA83I5bl1ZBx8RzfgCKm8T9Fl38b9p80lq7g4dmvYholQfhRoPgPA5peFZy_otU2aIIQl6O7LZ-WiGGkbZ0MHv3hTE7mwwQ6acQdbCf_oBOqRF4x8F-1OjTbV7LIx2vNnTSELAlfpl0vpBzBckxy41HQwpW1ddcPOEIZ_VYLHvCeedujsdKhnG3abTz45vDGtl6O35GlvhYTF90QJ9sso78gRkPhnycRSkLnN97W42OycRPzXD8iPGK7Ry49S9IMckrKg3wSkN_M1EZYEXwuOp_I1PDFd_16xXNAtZ3_i1cGQH81FM-Iy9b5Fs5nPevhf_aSqoRrSamSaHT4A__roIaxgtIpFZGGxaoA1-l6AHasS1jxaPGXDFexjztYvGsi3mDBtpPgKf4_ucXzsh5wzTos5g6_JF1vrrlm6PLvQ5DoThbJ_tyshOMVaj7mrj-ALnUzADOnxZ5R0tlDV3haTfs3aAGoW6jp6WQWmw6pXhjwkSNXF_hnseIVkg5x38XAt17EuG2tAsI_hC3z9deX9ja_L3xLRZa7DZY9F1Hd9qsMPup0XZA4czkIkGTnGuYOFULSiUVa5yfoz2l_uo7-6Cu3lC4gaartR-wAcGsVckw7n4kEEmeT7XZE7zLZOFMxHTtqnbBdzlawJYSePIbZUIySiPwE7hVzV4PW8s4VxQRBYj3MnirLl1XVYod61zgnpkJQ',
   'coverPhotoMediaItemId': 'AKZrisBR5a9DpULsiWKlUHtFkkIFx2YTgd_711WFadJPq3-1HbbpcKnBjq6aktxDmt1Fa3xWehhvM5n9rIa1H5mUFw287WNDgg'},
  {'id': 'AKZrisB0YOifFHJhcrfysBkRnIFSszZuMbqV0hSHYLjcQuTpKWEXyTeCxZNzXLAMVyn5_mfy5AjX',
   'title': 'Eucalyptus Plantation Technology for higher Yield ',
   'productUrl': 'https://photos.google.com/lr/album/AKZrisB0YOifFHJhcrfysBkRnIFSszZuMbqV0hSHYLjcQuTpKWEXyTeCxZNzXLAMVyn5_mfy5AjX',
   'mediaItemsCount': '9',
   'coverPhotoBaseUrl': 'https://lh3.googleusercontent.com/lr/AFBm1_bcY-9hO0nEWc9gQr3laHmFIDwc_AWZoJKVTS5jt8dkYICkPAtGW_86re6SD0b1056SdBKjXLhoNDsd3uKj4mbqOaO9p5PcH02vBjOByMmmGUBprM5UUhXjlmPXIOxoEbh1D4fk5okRaPbhga8yTIuoP1bCQpylU6eH8T02D6v-76wYd7hIgzx8nJdOb4b82S7T35ChixoNOkjBQJHooj-ELZEfFPLCtjGM5ExiowUIm24buTRynJPqVmiM0d5OCL7gOrwvQdl2490f1Q52YPC05uLA5sd_mzlzIVxHSiyUi7NQB1Ix1aCaQFlj8yZCS-y9aKvHusmkTT9zGkDShe9Inx_I4q-hxKCVtr4vIFPkyfEeiE4W6J2HM0gX5kU_lQekPiN_Mc37EFq27ls2F_VG8JbCMzCcOLkoMi_iGeHy66YKwgLIEYeLNKzQ1kNPCSkjN0HRe46irbhLXpEqPnrW69sXxh1WOVgRozSTEI1CK4SysxD_B5I29jQvhtCxdi5F5AGsQirgIZPD4hPBTYppLPEZsRRAwVufk4xboL7OVho2-LLpwGSCf3Xjjzka5DHjhT8t5bpZqxFxzSw7gkTyN7D6H0NynJ5VW7oo8iX0dcI2o5Lti0m3ZDyWOPXbD5SmR2ITJ9RzJweLWRbVxWdyxxUep9ROr38kY454lsgSWrxxngDD_etXLX9Vc1QqT54hj__4HnUMxcPz4vNoqOdQY_yiVct3quQgsJMxWitecF5G8rxN4Hh6fTnDzGBNqLqPcIbasdX_rlXGXK1zucTy_h7lHY73OMG4DbWvTLIOowG1d8Iq3JREj6_xbxKvmJAOzpfL0rrDVZiXOg',
   'coverPhotoMediaItemId': 'AKZrisBcsUCGc3WCspWG8Qqkmm6fa_MdDUCT3GigzFvAO-nHaxvpj6thAuydqsVM4-PkpwEYNHa6UxY_rGV3CeK2DhVeRKiWCg'},
  {'id': 'AKZrisCtgzOqloGTdaJBSOSIpRX92iXECX8PVtLSjZ5tBbhJgJX5_FQJyZaF7f_ZVonnjvkdKEdc',
   'title': 'Ailanthus excelsa Roxb',
   'productUrl': 'https://photos.google.com/lr/album/AKZrisCtgzOqloGTdaJBSOSIpRX92iXECX8PVtLSjZ5tBbhJgJX5_FQJyZaF7f_ZVonnjvkdKEdc',
   'mediaItemsCount': '8',
   'coverPhotoBaseUrl': 'https://lh3.googleusercontent.com/lr/AFBm1_b5s14aQ_4L9x6LUYNZneoMkvbTrJRm97-cDbyTp0YjtY-h3AFkIFoP20e80cZNZrE4PjxKs3tw5UXoIKBMLyq08Gp6kC9VIiD8QE8N9M-SVEYp_L6nAEEtn2Bex85B_Opn44OmIr2zoyh0nA5j4ibVgvvLIGdw1MDf64FJYrG4PtzHKYGiU2RMbUe4-0uM3k51dFZgCxuR-GsV_o0C5-jNyNcWOm-lCuFXYGEKzj_KnIyEhBDR-N-eZOuAD-MFYE_JdJ2neFLKGK6UmywegWkgGswkfrl8OfH3FKYXAOsvBjjCLXeakeQgetn5sZBigvLxOb4ccWgfK10AMdHHiOIts2low4CzO6Et4OQ4kXA0iRP864tbOmZRCaTxxwOOaWXclL-WACKGUsJFjAdrWeu_aPrs3RjPwsPmPXi3re8Wzwtv0S-h3GNVN7GUmCad55ViVuUy3NBlQoDneYo8sDaEZt9osAM0T-Y2bNPLZErbaXlijt08fcuyh9vd8eLRpY4gMT9E-nLzjJoZtAdEdnyX2KzwPQC9sG1MvlT8Km4yPakVh7ZQotdR_u1NoEn1siot2VgIk3wRYfjqfA0KkCTZRR2rJZ8ciWwJOSLyvWUquePk3U5qS5UDa9E9TNmNcypLoEY7fhfsllFxdnjyO_8srht6EJfwrX4mOhaHz6VRNNYBOe2crpwSEn8OTLXkndfPAtgwT1pVWtBVpW1JIXafQdO0F-hyUhdLk0do1wbGT_ufzs9cpolZvSx44za8vO_lpBUUA5ZhaURbMbLEb0L5yRXMq06SbN3JgHoys1scKuGcZjAIcYuE00RsSpWLtsDJrpaHO_qjRlOA1w',
   'coverPhotoMediaItemId': 'AKZrisAlbuyfqrn1I5fCFIBneU3w6eV02klbJlONqNv2pi_rbrtfc73UraM2XglSKfZIrtm9plPpceHReIbGgUfXDm1FfGwJiQ'},
  {'id': 'AKZrisAVzZSewnJi_bardRVxJsj-URzHlVXJqgUU7IMjZ4gmhO8BrdqyT1Fv6WDKvmPsFUD2PRzA',
   'title': 'Tectona grandis (Teak)',
   'productUrl': 'https://photos.google.com/lr/album/AKZrisAVzZSewnJi_bardRVxJsj-URzHlVXJqgUU7IMjZ4gmhO8BrdqyT1Fv6WDKvmPsFUD2PRzA',
   'mediaItemsCount': '8',
   'coverPhotoBaseUrl': 'https://lh3.googleusercontent.com/lr/AFBm1_YLG-mzG66_VXXvkPVijBO4II1xpBHBeYK4KD87z4Lz2Jj2-ypEy7l7R_K23Dhmt9lwrYZ4VHlaRBlNV8oIa-3xPPx8ulLP7fQbCJwElSFCXgo7m6836mLjF2WG8cjqoWs8GaAkiIJ7ArXG_POVstjUSyR9sIl4o2vstB4bFdphAsRDH1I4YCfEfTL9SF13N2VfEtwc0y529xAtgxJgXlwbMgbpGStWzXnM5GAgLOWwmVM09gz9Jfvu5RlW9PTmh5ey4aXkWlv-p0tm5i4LzmmNkd3L9Gl8j9oM0TRVu6oBxS8wMpbbkLVpgAUT3-wYWo8NjqjtG8zmDMWdldXKX5kJffQ7oNB4yEwJUXy3GkS0wrg53-8GaQuG1v4jpODVZa9iFNvYBrz4dulMTDr8M_ZcBYn7Vo8ALHUEm7vPS1VzmiC22HhJtR3D1HK4Bitzx50_SCTmZMc9Wd5h2ISUNybGbIGongXXKXb-mm77lyhihy-wDCZ2qk7qMfJOyTwGL0gRSJ3kWlMi24x7_KBjSboka8QPvuaYSaEF8tUnnizuFAb8-ZnbcqjpviJnvyUadqLpJYzpkFLrxPZgXNb9xNxeD1W3QSdIoXmFPq-P9uot729WIdAjobBRGfyg1h-DXlXiAGDolx2mybdb_eSQGhcXmw3IkhuatahuKhjsqB5bYRWsoZIeZITp29sFzxR8oiedY8wH0t5t-FBQcJ1jVwrEOZGQ84hhCs9kY8XJSAeHhVd70NkcscoQHeHFVo4xhvBPlptntLJH0pfT1yPYngp-1Y9E4BFeNma2LFHcNgOU6QYvGcVqID6BsyO9Rp0eCnJbWOGs7HHEa7jF-w',
   'coverPhotoMediaItemId': 'AKZrisB_AfqW2BFTrw_ej8tZCQ0uiZdQue75Od2MZVufx0e1Vqq6DwelS1wNrAWhCq3lq5LnGivffXUMbr8eDMjLQzjYsWv0rQ'},
  {'id': 'AKZrisDxIL_WaaZpXtFPO5r_BM59IRB9mYJusKpZh-XV88JtWM63QxUeT7ztrg9hWRCfejQ2M_GH',
   'title': 'MELIA DUBIA ',
   'productUrl': 'https://photos.google.com/lr/album/AKZrisDxIL_WaaZpXtFPO5r_BM59IRB9mYJusKpZh-XV88JtWM63QxUeT7ztrg9hWRCfejQ2M_GH',
   'mediaItemsCount': '10',
   'coverPhotoBaseUrl': 'https://lh3.googleusercontent.com/lr/AFBm1_ZAOsNKFZ7hy5PP8ypwdHGfjHGplKGi_BbPUo3H9VCS9hR6eubzs0JkIrOH5Z1R_oWhoVF5dQR9bcvPokrlgC1Bk0Iiku6RTTFvC1xUSI6uqBi8wjipE1HCEsTtd9zj4bhmI-kUWPDXA4bBhMaYjEszfjU_Q-XGavCllN8q425v9gQkfdJBrQc4DRLCf1rnkugDFT8bnH5PmurEIoc-4sU7GhDbByLiVZvwAJaqL1hPsFleSJrncsTu1NK0t12anBWTB-QglY6BqCmqMyR5kk8cM-3XtiaizBRGdr7v1mRtb9U1sCSN9yKDIBPUV89_uPSsNrn47rtPlRoWj5GsXO0lnPav23nZJWgtypK_Vl-00CQviOoLD8k5-GJUm20WrtGQUMESbOuJjxkH2D8ccLVrS7uLn_mbPu72EYGLZn6x5lPRNpx8Bv3qSzzT_qd5twSegDWecsPMoYd8uV1y7gnPPkloDbOcvZUy5b7zpG6dbOwAaV_NFybzFHfCgbdESlEg5dCsT2HvU4k1UZiMegUez7-TA7cC0ua4JUt1CbVKMCXt1Su5EnT5W-XNMC5YZQ7uo6bt8uT2Ch5vgb47kvG_y6hoImtDUVJ6T5iMRvZTN4PYG7IhIPtS-JFkf-iqL8AI1wXQ1-wQrtbd5IwKUW2SWg742vPt4Y561AYTkOYt53H4iRZjqtcWmTxjtRTihs39PYPmcvL3iWvfpJy5Iy72QcPU_53Tvnqrx6ghuoqqQf54d4VS8-011WB8jusEyFTFQgXUlWqjwwPpLZiM0jo1CD0q2AakwSxXyA9fp2_HKPQpKQjPtXAFspk8OuozvPv_Y3PwFm80tcUE-Q',
   'coverPhotoMediaItemId': 'AKZrisBLaPmIwY3EnPlk-Z_6l8NDUtYvmU8K773anyExPY0N7gbMr7fw2Mzy1AZoJpx-MhWz5KGBJWUpT8diAHueRLaQXO20xw'},
  {'id': 'AKZrisC-uq29ohlGL42_9HTTsTxCQ3Di4DFqsil9qh5pouDQDX8nCE34Q_HrK-uv--fhckgR3bQQ',
   'title': 'Book Photos தேக்கு ',
   'productUrl': 'https://photos.google.com/lr/album/AKZrisC-uq29ohlGL42_9HTTsTxCQ3Di4DFqsil9qh5pouDQDX8nCE34Q_HrK-uv--fhckgR3bQQ',
   'mediaItemsCount': '2',
   'coverPhotoBaseUrl': 'https://lh3.googleusercontent.com/lr/AFBm1_aCuJgo0fV7pDHB716hknaoHYqCbxIetUwHk_iCH_tZ8YxpGqa8K3w27G7KoHmhLDM6xxKUUqN72LseVLCweNmxAnlDPEhE3XwbPttyb4LpAtyjw88t4jzktI45qdbVRDDQ4MLuzkt5DN48KKvj4fVFvXRJVYgJjOWIgvPePuwG_9L0L3H221HRwTfGW5yf7o3OmehnEy2yTN6oEPokgCwmt50gWATAPAhomNOWBVefH1aoq7LZR-8C5fDmwTMrHGq80Lz3DcKNLTrrn3TsbTgVfT09GLChWERnUQQGJaizx_Hk8LiaAz3OgFiv_WH14fqVg8AIItzCdyspiLbyvhlrF75mN_Czxx6PeE8OwK2W7Kyg6b4gseaYXT5e0pW1ewQQDgbDwMUo6FItEA-5xcfkyaXUZiWHY0GVf_JRhHPBbyAF4zCt9R3tSOQp8BZQoUufSd_c34BsVGqp9mdmgRHIhCewIUt3YevoAVG9GwKoQuTCnJCyIcquMdcpSG7XitY7g_tg2ClekZGOCtzuJfbXZJPI6SuPCgFzCq_1yNLhu5mCcTBN4P39s3AhIjZcTvfNzSAkE9bIj8FviZUqSaTq4o1j8zEKEvy2U49s5do2vZfMc8xi3lqKvslGexjVZrk6zwVSX6waJo7pKWVuBggEyrT15JZ-eulz4CEMyFMqUo6a6O2hOJBlmZyY_OCpVchJb8T-pEIGxFq2rlfifn36bq95fKy45dx8rGZjebzltZJgp0Pl8HG3PSApPn9LeNdzsh9x29fOANR63tFs9IptiOVOn3OpAoa_3Q1AMaR32Vg8SqdGA3SIrkxBJ9rBDagBPPdH1iTNkeuO6w',
   'coverPhotoMediaItemId': 'AKZrisB8aMMyrmpejSBq4cludQosBIYWHxY8nfkI6H0F_yJLCzglwVEQ5kOyyhIbpt1UveRVTx65srO1zNLp8QwlzkZZWY_BUA'},
  {'id': 'AKZrisDcVWODBYBOos585TxRS9ExDufx6Y9esq8xknHAhcT0EsnropH6HnDD3VCoq9k_iFKHoeuA',
   'title': 'Book photos',
   'productUrl': 'https://photos.google.com/lr/album/AKZrisDcVWODBYBOos585TxRS9ExDufx6Y9esq8xknHAhcT0EsnropH6HnDD3VCoq9k_iFKHoeuA',
   'mediaItemsCount': '6',
   'coverPhotoBaseUrl': 'https://lh3.googleusercontent.com/lr/AFBm1_at7YkhJECqX_XYFh9WOvjvDjWoRE8VuBleC7IwMW2yJHeJJWWFOgYCzhH_lX3WZnP1-Mt1Eg0X3123z2ffE833izeFceGwHpUpO-OfRoJHk6TDlABw6y3F8hwcIYadlPXywO5xy-M8gnvQ4jS3VY4jsVD1pDGai6_exYeoQ0lioui6ev2FLCGF0cONHTTzq9CMs9NQzyVB6OPIFRzKCglstyM34vHlJ3MJ4QSone85fP_nL7gklfPRpk2IYtgdRuVmKNYrItXFR0W0prlMjTv5S93Tjp-R4Ds7LEQNvUMdzJH271p6Uqak2UgvcdOFFgkjIENJ-gKSdHHTvm0NOls5TBlfEVGZQVzpgBf9jtbsOpMBwGYCO5qlnc8SLWWli2bjpTUYrMFb7qoANamFom-BoUyTlPjRVbBsD8yB0HCiMg_Uz7pdSm9LN-6V1zhPANWJYS9X9KXubZY-0WSkiotbYl7KD2H9DUrbT9keuokz5R8Sv_pTu9WJ1JhmROXhw9RfCgokxEQs4cMSH4aycCsqYfICgr3HjdPV87h5h9U08pGtke0eOWuZhQeUTqP247STfJ8_LrgiPBvCN7Vnp0TMBK9zunapyYK7Lq_RU1WYm3_FMNuP20PZagSqFjTTlOcSVWsMMo4ySsHOPeyLndkv6lmJkAzB8XrB-CGUTYisPO-jajs7JjvcbzyOVZEQpIvpTQA30NycB45dH6Lq2KsTSrmaJ1L9ZCmULzTa9nATUredupI64jLELhd88pOdn-3UOndtNQ0gImuq3nowm88lxuYMyOgwQXssLTBLajqaogeqXjdhRetoUoqjGG7FDBAOJJkpKHWFgdT7pw',
   'coverPhotoMediaItemId': 'AKZrisAGcgBOTtULh_Xtz2NQAqCpFw-MuU8u1L-1VVcBk_znCw250j0_ozQiiq0czf3u2F9BtmJ5tSekVzFhJ05BTGt2M6UvPg'},
  {'id': 'AKZrisCDT37ocORitK3xHYC_CxMnfwR66MOz0cTnCPYUwuLKSCQSJSqMoXSVjYbUHse9E6u9KCo_',
   'title': 'புன்னை ',
   'productUrl': 'https://photos.google.com/lr/album/AKZrisCDT37ocORitK3xHYC_CxMnfwR66MOz0cTnCPYUwuLKSCQSJSqMoXSVjYbUHse9E6u9KCo_',
   'mediaItemsCount': '4',
   'coverPhotoBaseUrl': 'https://lh3.googleusercontent.com/lr/AFBm1_Y6jLZpZoy6tZDhi2_Pw-VRIGBT14oegMFRFx9K4NFLlukxCDvoAnhC9Buij6KKjGPix8jqA_ynNnDFD4Jia9EWfZltlRB0xIP4J4FPwrc45gkOAYzPH54H1eAin6ktETF5saAeuakq_zT81OKx9yzeuaXoww4N3Pf-fUpLjYZ0kn8zF7aX3cnC0I8CIMF7WhppDE3k0dAJKmFvx5iZzGaP_1Oy05TwRuuGHpu4DXjmDSAmMCYxGqeZkIEnnu_ji2BIm8C1HVL2cdA8R6xN7v2npOAulOmDVrt_8Kdq6u4wutSuCKUi69XPRh9ryCv9mgAkQqDifyuYuBmSYGaq1wsSr297rirEDv2VMH0M6Qpah48uPdgiP_e_Q3b3eM1uVrUTYrL9K-4eZ4Jqo29nmzBzPmvtWuRBxWny8nLLq4Z-rvhnPRpRs6kQV4tZaq3y0THDEA0zJZLhINlIYb3dDY74toUyuNe0-X8c-3kCrAYDXa4CN3_6JkJfJUIce1zrX4-pGdzHs861x2omnfiZQ-PmzSzqvaFMvRq1Y6W_hRVPIJuOll8Y8phlyc_CNKRagQi6AkFwvgl9KfXlJauGLS2TnsSwAH0MStPHO834h8cnhO6GvHmcpKtFETEdpPI62DVZQPJXncN30FwhdILsq1ODaX9_6BKA-z1MtyrLMZHkXl_kgJzCICXUg655nYC_PfGGMpLivsmruSFRZ5jJv0YxUyxAxE-AMM41D8aQ8hqjR80C0HNFG_EzjXNWlz0utZDEc4sIJNtcbgBXBFf2s2Tf1RDay5_lW59C871djcILFh173DWa_dkmAR35LJX16H_LvIXxOYRM9o-I0A',
   'coverPhotoMediaItemId': 'AKZrisBCe1NLoiOOCLAXxSMaI72ItSp0E0abYepUDl7GAc_H2GzcXgoQ2l2YcVnGqF-O7v7QZmgzc9HVOFPo7V_8FpMz7BVhuQ'},
  {'id': 'AKZrisAirepCPFI3LbDoxYVNl91lt2uZS7kW-nflGlVKQVwrWDxnkvf1yEW3ikFKpEx2SWpX_7V1',
   'title': 'பெருமரம் ',
   'productUrl': 'https://photos.google.com/lr/album/AKZrisAirepCPFI3LbDoxYVNl91lt2uZS7kW-nflGlVKQVwrWDxnkvf1yEW3ikFKpEx2SWpX_7V1',
   'mediaItemsCount': '5',
   'coverPhotoBaseUrl': 'https://lh3.googleusercontent.com/lr/AFBm1_YYt3KsXGNpb5Dn3zN-zH1AAq-Q0sIPfjWHJdAcz1Z3hN9HzfxSLYMblCN8Eoh46Ap70ffa-w8gPGWtRi0p2D31idB7m85Oi5jXaAVzNGZQfjmsZLN6MDvLCoVL32vtrUl8nGmaea911RmFFBxxmX4eIvpfyMq7NZdZmcTCxgZ6fAa3y7spJN28rdBzXzircWFwslMxpUwsfcM0mLw_9-PBlH-2XvYwIP2zpFbJ3yDJI8-KzfEDETLST3EUtcXZqzQDjrohngIg1O-FFX_Ov4Td9BQ9lcUUNdm7biGVVwOCYAOJTHJ7698j2Ic7CYIrWlYLZa2rJzmjofyMf6tk2Krhg4VVsiUnMfL2XDGDzHXZTSKoAcpsWNpJg3zZxI7DvYaNwSX2k81JistS9LMD1FH3yEONIXTUdnn9bIEGu985OAqzYBMoSjbD6oG-86LI9RzRh1InGrRP_wHRAWSYczh3a5N38x753H9qt6xw_2OzKYJZCmOXCsMe5gOnirXUAiF3NkRvx0dnUNR8QZ7SP2BBOQHe8DQJ47viy0_R2ELqAc6RshIcebWt3ed5TRj-mjVTspBzkKkYQSzlbWbIBYbs03lzUpzStoywtoBhpx-drlORz1OmOht2OEE4ZH2ixX9B09I19L7UxzYNgFM5AL_bi8CH000_vRUAe09ND0F4ksXGmx_5JAoWwd7LVCAfmW0Xp9rpg44Vts9EFgGfzbEXoW0B70KZWzwig9BkV-Y1SK_MoC8qJSKCYrUwtVZs7AFjvWU5iiY0yZUNd7nD1Rlc9GsegePwXlh6vRnn6KStSLCHCG9ol8aeWZ7UAW7w61DAb5VI_ZFl6VkGGg',
   'coverPhotoMediaItemId': 'AKZrisAVGORpih3dXLY1c0yalbA9JutpySC9JEcnMyJn-1lilsE7pMRmaJjyLuGE624r6K7BYkqWgA3767TZFTk_I8JS-wOR9A'},
  {'id': 'AKZrisAmG9SMAT8sj8IkADES42oBnqF2nCChGAznOYlofr3Eyd5TqZHi-xe5zscdYBMWAwvu7ALV',
   'title': 'Book Photos மலைவேம்பு ',
   'productUrl': 'https://photos.google.com/lr/album/AKZrisAmG9SMAT8sj8IkADES42oBnqF2nCChGAznOYlofr3Eyd5TqZHi-xe5zscdYBMWAwvu7ALV',
   'mediaItemsCount': '3',
   'coverPhotoBaseUrl': 'https://lh3.googleusercontent.com/lr/AFBm1_YrLEco7MwjZvccqBJDUzmHpDrBGguiC868x325AjhcrgfvK2Sl2dqLLLWNMzIoNSoOy-rz3Z8o_KutZiLnPGLsrG9ZiI4ZDy2ke89fcSWh5dkkslYvf0VUxAS7RgSG4eAPMe0vJ1pmd7K4RDc9TzLQMCRITEsqsZNtcSFcD6xmowXjMZ_tw_FlQ2YpQDLT25tz0Dt7OStvLq8wBCTh9VuhgbA6hEJNbuna4panp9JyQvLyThdhQ5_vQiCcyOUvYS7xBvMadZmZ95eGasMgxhE0PpdKFbLa2EbDMOH6wUaRsp_PE-hJc5Ypl4SuJLxptwRLA9mvu1Zk2bk0YJNNvIpkDAevC9qmzCs337bZYuRHh36q4OzmwSa2lUsaOWVbSZw6GPjTZV5Ur_0nYG_LNuJIkdh6u1wYA2Dyajl79gXnrLbbNR_0kh063E6512AKAuuQaw_sbp-l_WdjKVPyEBxBFqDtC-ynMUY3VrKXP6pU6gBCER6U1PJKiotFqA9sjg-TGgbWUv_r2bKxD3On6U-P3OZtGCREE2K8r1XS7YQaznV_cB7fx_zgx5NzXqjYdvJ-IVI2Rwnazl9eUMKSg32V6QlaPqYT4PNtPHTh_iF0q_anAvdNM64MMgHe3lMu0Bg7oSdDEvAmbBEyGe5o6A9_fGRqxSUMLahfsXBh3IOpcM7evDTaqsr_HyPLGAvCnCeagmA0xY2oEHH7X3PQ_sIEfpBfH4rUSPprxctZZc5p4brm-7AUKxDsMzTvVTEELrDtzdxNhv1-0kXT8r-vAZLHUWd8grXyZFQ4sHIvwQ6kSjtGVRYt6AiyaSNoSOD9W8Vo5LMD4_LGifrTzQ',
   'coverPhotoMediaItemId': 'AKZrisCn4ED7nD_vlu2Ctg26J_T6Cy_CUDQR9lYvZbYDJafSmz9q65tChonSOBdblUeeI5rd60tCNLwb4NbNpkJUevr9CONk0Q'},
  {'id': 'AKZrisDe8o_3tqdOOhsE-NsMuYUbTohNq9Umweuu6VXNnNlb5zu3Hy9PFY1kguYvvu7WCBGSkVsX',
   'title': 'Book Photos Mlaivembu',
   'productUrl': 'https://photos.google.com/lr/album/AKZrisDe8o_3tqdOOhsE-NsMuYUbTohNq9Umweuu6VXNnNlb5zu3Hy9PFY1kguYvvu7WCBGSkVsX',
   'mediaItemsCount': '4',
   'coverPhotoBaseUrl': 'https://lh3.googleusercontent.com/lr/AFBm1_bMcVnoZ-rQKfcfF4e8_uXAdhbPXjkLm0UwXdUZk8ogxSssoN79W3k0F_LOXoaanu1JDh8p_sMCQlDteHM62ZajLKvLOyCbuefHFnwlIOlfZ5yjLwpQ8YRtfxCN1tsGedVuL6h8h81bo2vhF6hMAqV8F6YDpphgLXyLjxET76ViX-654hCiVPqByMw-aQ-zqSmY1Be7ZQUNm2UEMl-E-A-JuQXozulskBIr1szWcpt6uGhr_FknbHkEat2R49MJZ_d1yvs7x36k0W6IMiCOWn2hlcZ5_PF5BxdTfoGJm3xL87yOE_hsiwHGx4fKLOiJsJEc-UsM7hlQ_n-guVFofXGWdZt-rIZBKAljCXr7-mmQeO_CnOHcTasDyik7PLuJLFho_-SBuWAS0LrbmG4-N10_fNfLOLxrFATNDwnfh-I3PcvKoW3iix3GmCqubheUee0oqdJFH-aJ52Q8pyrdwSQudpCm4SiODVYOib6Ims22L7JMQCof5fv3ccJ3JgnuokRq8pCG1NnXQMi6KMqgvouLXkysbOwKRym5hpbXVBquFMwiMkYrjNZqvSlTgngWW68JZFpvfjYPKyIXZuUCBv1HA-k35S97RBOeP6cHWOmzt91qvQcXvVDoKj9bnkGlko9FpjH2YheupgLTFT_0M_OcOG-PlKn2UWce8nG1gBd7OQGHVhDmkADSUduAF9rKDIKOmdsooDkExjIAySLZl_qBWmeAYguy66XtS2EyUAGFE4cDCZ3Bdzh5TCm5pkcYZjjQWrqYqDrIUPKBn1ah5cuD-FBAFRkvxQ1MJWd3UzbP7rBdDWhgBrQ9Tsq8AS25iYmawJed30gIuu7UPw',
   'coverPhotoMediaItemId': 'AKZrisChr61Zia8m515cbe4TcvSw4flPDsrs2NBqKnldiO7hWbDbDtoy9Pf_CRmm4mWYTWVKTOU5GFjX5Bcgd7p7jD1u7AQNig'},
  {'id': 'AKZrisCB59njJJ9YLsqhSoJVcwJT6VAR7MgcuQH_J9mMuisBgr39THcocG8V7Zb4PGFyKjSacnep',
   'title': 'Book Photos kadambam',
   'productUrl': 'https://photos.google.com/lr/album/AKZrisCB59njJJ9YLsqhSoJVcwJT6VAR7MgcuQH_J9mMuisBgr39THcocG8V7Zb4PGFyKjSacnep',
   'mediaItemsCount': '4',
   'coverPhotoBaseUrl': 'https://lh3.googleusercontent.com/lr/AFBm1_ajC25p_gZPdYmjrIEV2M6ehYBWn0cHTeX6gBviHfhYwpXlnv8ubZ4hULVjiuqf27Ruk-qprzjtva0kAMzsOHND33en583PuscSBgBhKqBxivWwIHCkl4uzaY09rQ-VhXHsRqnAAPoKwihuAvfZTzCCdRj5QbFEP5aocqyMJvtWbMuoNydVNvhF2KxD2-4Fmk4ldVr22Di7BtfbnaTOVuLT58PmWj1ygIvQLpJVhildQ7odFcxN4hV6RbGGq1JP3Sb-2yyoyJlMai-tyPDzC0RXyrCJEtY6i2tnryOCeSiwAjfIbc7bnil6GQoVVMJGUGxElJOqtea1TZP0B8Yg_pEGdfTU19ChQOA8QI3FUlAlq08ej3VUC3bUEiM3iH3DIaTzos6yzAVD9xvIBQKqlkadLeaf9KI2cnpFD-IwZLQQ8Iia0guYX0Jm5GYTsFhTAXLM8u8UbBM6MlB8DHYdKprngnmf0bYWTsWSqKbhQbhBA8N9uS8bimGmxZBiMficjhJq3jhRRM7Vb8h5mlYF8FsBdoQj68Zme2zcvFHylh-wNAj9zuhosG2EwGSeWTIJWspeUUCWnbeu2KEZX-vz5_egKwO_mZ2g6ByvpJgv0uKQlLOwWpHNlCho0YHPlibgiMXks7l9RJOI8FuoURF08iwEYc1ZAacKHln7JNW31WYZpcr6_bcPjh0XEeGQML2zd8b7UO3tlLXx2rtevHLn8K73FBHSghasEsZlqZM6R-MyF9TD3aWC-5aSGAXRGFufA3xM0-QAmyd5HLl4ZsgNp-uNxm33h-RjHWTDHpB2QN6NlP1jK4--mABczmPcHf-v1WOGNgNkxHeVz3DIDA',
   'coverPhotoMediaItemId': 'AKZrisB_oe5ItLLQldTclEk2xWsVelhD90ATkzeMOqX53jFDNPznzKBJMT_KKRgnBeZuzgHYrG7HV5YTBoj1bd-r5SRjvq1Pyg'},
  {'id': 'AKZrisBSqwsxYRrDw5Z3LhCcpI1e1pUxxewwnNt6QuxvJuzBK1N1bZfA_dR8qZbh6U_vLGCrNzxu',
   'title': 'Book Photos குமிழ் ',
   'productUrl': 'https://photos.google.com/lr/album/AKZrisBSqwsxYRrDw5Z3LhCcpI1e1pUxxewwnNt6QuxvJuzBK1N1bZfA_dR8qZbh6U_vLGCrNzxu',
   'mediaItemsCount': '5',
   'coverPhotoBaseUrl': 'https://lh3.googleusercontent.com/lr/AFBm1_Ya9wqgkJ0g1SF3rTzWWSG1CYeLJLjA5RaQ0IkogZ8siCbGI0IybtFeHSmF0KF0Guo1StfrDWRqdP5np28nEm13AMdVzbd3_zOk8rxFWQSvjmFCh6EhIghWjxMsKvMXC_-td4fjNCdSTGkZk7EFBWRI9qyH7GyLfozT81R0gBIjh1PoMF1slh2uhzxFczS-GzdshADxmqL1DBKP_U9vnyIK47RBiRe7b0voC7kq_0XcOOilxpm7VX1eIclYkLc_yiRaJBoHoDYdHV_oDZTYgZwJCIqHqmHeZhYm9hby1AAOD9NilapeXiXopaJj8ide81XcabXJyBFABnCdG-Uybm87urZGg-ept_8rAk9ZZliazME5bcCmr-NPauSLmanNXm_hCnjvEd1bFwCQ1w4YwKoh0e6L3FzfRNcNZ0QiXyX_i1UWVfY0drF2L1CbhogB5VxwdONl5dA_iWuQnO8HXEuMQeoNHKEEBEjqm8MZEEAUw-CHYnvT4S-0emQwXGfK6n1GPk3auOI_XbbX8FWaUlvvjJlvKGGidqIRbi4jKyLgiCExJl_2QTOCngvAWrD4gM4I-9eXYJ6lN5wZ9kQmUXSUz3NMIbgYS2DLxDREeYaANjRD8o7SPmofUHxLtofC7HhvWjEaV0-LGgEj8Ch3WcfJRqHE8JHeOXkgpmzA2YZ2OQ17JHmpfnJtGJjaB9UsWrsEQ-vQ5MWjXCtqZjrJ8c-i5hoTXxfYD5pmhQo3NW7BS-lXNRjnRbWMlPf9731X8tJiUl1urCUSpRVBB5HvrKhzIi9-phJalRNuRF8zrpFQwTa1OC1DzbHDQwFf6oWJaS2rSYLT56zabLbdtQ',

In [13]:
data_list = []
for data in data_dict['albums']:
    if data['title'].startswith('Book'):
        print(data['title'])
    else:
        data_list.append(data)

Book Photos தேக்கு
Book photos
Book Photos மலைவேம்பு
Book Photos Mlaivembu
Book Photos kadambam
Book Photos குமிழ்
Book Photos
Book Photos புளி

In [2]:
UserTypeTilesMap.objects.filter().update(language_preference_id=2)

55

In [7]:
import pandas as pd
data_dict = {}
nursery_office_obj_id = 1 
nursery_office_clone_cost_map_obj = NurseryOfficeCropPriceLog.objects.filter(nursery_office_crop_map__nursery_office__id=nursery_office_obj_id, is_active=True)
nursery_office_clone_cost_map_list = list(nursery_office_clone_cost_map_obj.values_list('id', 'nursery_office_crop_map_id', 'cost', 'from_date'))
nursery_office_clone_cost_map_column = ['id', 'nursery_office_crop_map_id', 'cost', 'from_date']
nursery_office_clone_cost_map_df = pd.DataFrame(nursery_office_clone_cost_map_list, columns=nursery_office_clone_cost_map_column)
data_dict['clone_cost_data'] =  nursery_office_clone_cost_map_df.groupby('nursery_office_crop_map_id').apply(lambda x: x.to_dict('r')[0]).to_dict()
data_dict

{'clone_cost_data': {8: {'id': 1,
   'nursery_office_crop_map_id': 8,
   'cost': Decimal('2.00'),
   'from_date': Timestamp('2021-12-27 16:28:23.249283')}}}

In [9]:
import pandas as pd
from base64 import b64encode, b64decode
journal_values = list(Journal.objects.filter().values_list('id', 'title', 'author', 'published_on', 'journal_file', 'category__name'))
journal_columns = ['id', 'title', 'author', 'published_on', 'journal_file', 'category_name']
journal_df = pd.DataFrame(journal_values, columns=journal_columns)

for index, row in journal_df.iterrows():
    image_path = settings.MEDIA_ROOT + '/' + str(row.journal_file)
    try:
        with open(image_path, 'rb') as image_file:
            encoded_image = b64encode(image_file.read())
            journal_df.at[index, 'image'] = 'data:image/jpeg;base64,' + encoded_image.decode("utf-8")
    except Exception as e:
        print('ERROR - {}'.format(e))
        journal_df.at[index, 'image'] = 0
journal_df

,id,title,author,published_on,journal_file,category_name,image
0,2,Casuarina based agroforestry,IFGTB,2021-12-29 13:41:42,ifgtb_journals/Casuarina__based_agroforestry.jpg,General,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAlgC..."
1,1,Calophyllum,IFGTB,2021-12-29 13:35:14,ifgtb_journals/Calophyllum_Tamil.jpg,General,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAlgC..."

In [3]:
import pandas as pd
institute_office_obj = InstituteOffice.objects.all()
scientist_obj = Scientist.objects.all()

institute_office_list = list(institute_office_obj.values_list('id','institute__name', 'street', 'village', 'taluk', 'pincode', 'block', 'district', 'state', 'is_head_office', 'image'))                                                                                                              
institute_office_column = ['institute_office_id', 'institute_name', 'street', 'village', 'taluk', 'pincode', 'block', 'district', 'state', 'is_head_office', 'image']
institute_office_df = pd.DataFrame(institute_office_list, columns=institute_office_column)


scientist_value_list = list(scientist_obj.values_list('institute_office_id', 'user_profile__user__first_name', 'user_profile__user__last_name', 'user_profile__mobile', 'is_contact_person', 'expertise__name', 'user_profile__user__email', 'designation'))
scientist_value_column = ['institute_office_id', 'first_name', 'last_name', 'mobile', 'contact_person', 'expertise', 'email', 'designation']
scientist_df = pd.DataFrame(scientist_value_list, columns=scientist_value_column)
scientist_df = scientist_df.groupby(['institute_office_id', 'first_name', 'last_name', 'mobile', 'contact_person', 'email']).agg({'expertise': 'unique', 'designation':'first'}).reset_index()
scientist_df = scientist_df[scientist_df['contact_person']==True]

final_df = pd.merge(institute_office_df, scientist_df, left_on='institute_office_id', right_on='institute_office_id', how='left').fillna('')
for index, row in final_df.iterrows():
    image_path = settings.MEDIA_ROOT + '/' + str(row.image)
    final_df.at[index, 'full_address'] = str(row.street) + ', ' + str(row.village) + ', ' + str(row.taluk) + ', ' + str(row.block) + ', ' + str(row.district)
    try:
        with open(image_path, 'rb') as image_file:
            encoded_image = b64encode(image_file.read())
            final_df.at[index, 'image'] = 'data:image/jpeg;base64,' + encoded_image.decode("utf-8")
    except Exception as e:
        print('ERROR - {}'.format(e))
        final_df.at[index, 'image'] = 0
data_dict = final_df.fillna('').to_dict('r')
data_dict

ERROR - [Errno 21] Is a directory: '/home/kultivate/Softwares/jamun/jamun_admin/jamun_admin_docker/media/'
ERROR - [Errno 21] Is a directory: '/home/kultivate/Softwares/jamun/jamun_admin/jamun_admin_docker/media/'

/home/kultivate/Softwares/virtualenv/jamun/lib/python3.9/site-packages/pandas/core/frame.py:1549: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  warnings.warn(

[{'institute_office_id': 2,
  'institute_name': 'IFGTB',
  'street': '1',
  'village': '1',
  'taluk': '1',
  'pincode': 653544,
  'block': '1',
  'district': '1',
  'state': '1',
  'is_head_office': True,
  'image': 0,
  'first_name': 'Dr. Saravanan',
  'last_name': '',
  'mobile': 9442143520.0,
  'contact_person': True,
  'email': '',
  'expertise': array([None], dtype=object),
  'designation': 'scientist',
  'full_address': '1, 1, 1, 1, 1'},
 {'institute_office_id': 3,
  'institute_name': 'IFGTB 2',
  'street': 'main',
  'village': 'Coimbatore North',
  'taluk': 'Coimbatore North',
  'pincode': 641031,
  'block': '',
  'district': 'Coimbatore',
  'state': 'Tamil Nadu',
  'is_head_office': True,
  'image': 0,
  'first_name': '',
  'last_name': '',
  'mobile': '',
  'contact_person': '',
  'email': '',
  'expertise': '',
  'designation': '',
  'full_address': 'main, Coimbatore North, Coimbatore North, , Coimbatore'}]

In [11]:
scientist_value_list = list(scientist_obj.values_list('institute_office_id', 'user_profile__user__first_name', 'user_profile__user__last_name', 'user_profile__mobile', 'is_contact_person', 'expertise__name', 'user_profile__user__email', 'designation', 'institute_office__name', 'institute_office__short_name', 
                                                     'institute_office__institute__name', 'institute_office__state', 'institute_office__district', 'institute_office__block', 'institute_office__revenue_village', 'institute_office__image'))
scientist_value_column = ['institute_office_id', 'first_name', 'last_name', 'mobile', 'contact_person', 'expertise', 'email', 'designation',  'institute_office_name', 'institute_office_short_name', 
                                                     'institute_name', 'institute_office_state', 'institute_office_district', 'institute_office_block', 'institute_office_revenue_village', 'image']
scientist_df = pd.DataFrame(scientist_value_list, columns=scientist_value_column)
scientist_df
for index, row in scientist_df.iterrows():
    image_path = settings.MEDIA_ROOT + '/' + str(row.image)
    try:
        with open(image_path, 'rb') as image_file:
            encoded_image = b64encode(image_file.read())
            scientist_df.at[index, 'image'] = 'data:image/jpeg;base64,' + encoded_image.decode("utf-8")
    except Exception as e:
        print('ERROR - {}'.format(e))
        scientist_df.at[index, 'image'] = 0
scientist_df

ERROR - [Errno 2] No such file or directory: '/home/kultivate/Softwares/jamun/jamun_admin/jamun_admin_docker/media/None'

,institute_office_id,first_name,last_name,mobile,contact_person,expertise,email,designation,institute_office_name,institute_office_short_name,institute_name,institute_office_state,institute_office_district,institute_office_block,institute_office_revenue_village,image
0,2,Dr. Saravanan,,9442143520,True,None,,scientist,None,None,IFGTB,1,1,1,1,0

In [3]:
Forest.objects.filter().delete()

(16,
 {'main.ForestOfficial': 5,
  'main.ForestOfficeCropMap': 3,
  'main.ForestOffice': 5,
  'main.Forest': 3})

In [4]:
industry_office_obj = IndustryOffice.objects.filter(is_head_office=True)
industry_incharge_obj = IndustryIncharge.objects.all()

industry_value_list = list(industry_office_obj.values_list('id','industry__name', 'street', 'village', 'taluk', 'pincode', 'block', 'district', 'state', 'is_head_office', 'industryofficecropmap__clone__name', 'nurseryofficecropmap__clone__crop_cv__name', 'image'))                                                                                                                     
nursery_value_column = ['nursery_office_id', 'nursery_name', 'street', 'village', 'taluk', 'pincode', 'block', 'district', 'state', 'is_head_office', 'clone_name', 'crop_name', 'image']
nursery_df = pd.DataFrame(nursery_value_list, columns=nursery_value_column)
nursery_df = nursery_df.fillna('')

nursery_df['crop_clone'] =  nursery_df['crop_name'] + ' - ' + nursery_df['clone_name']
nursery_crop_df = nursery_df.groupby('nursery_office_id').agg({'crop_clone': 'unique'})
nursery_df = nursery_df.drop(columns=['crop_name', 'clone_name'])

nursery_df = nursery_df.groupby(['nursery_office_id', 'nursery_name', 'street', 'village', 'taluk', 'pincode', 'block', 'district', 'state', 'is_head_office','image']).agg({'crop_clone': 'unique'}).reset_index()
data_dict = nursery_df.to_dict('r')

incharge_value_list = list(nursery_incharge_obj.values_list('id','user_profile_id', 'nursery_office_id', 'user_profile__user__first_name', 'user_profile__user__last_name', 'user_profile__mobile', 'is_contact_person', 'user_profile__user__email'))
incharge_value_column = ['nursery_incharge_id','user_profile_id', 'nursery_office_id', 'first_name', 'last_name', 'mobile', 'contact_person', 'email']
incharge_df = pd.DataFrame(incharge_value_list, columns=incharge_value_column)
incharge_df = incharge_df[incharge_df['contact_person']==True]

final_df = pd.merge(nursery_df, incharge_df, left_on='nursery_office_id', right_on='nursery_office_id', how='left')
final_df = final_df.fillna('')

for index, row in final_df.iterrows():
    image_path = settings.MEDIA_ROOT + '/' + str(row.image)
    final_df.at[index, 'full_address'] = str(row.street) + ', ' + str(row.village) + ', ' + str(row.taluk) + ', ' + str(row.block) + ', ' + str(row.district) + ', ' + str(row.state) 
    try:
        with open(image_path, 'rb') as image_file:
            encoded_image = b64encode(image_file.read())
            final_df.at[index, 'image'] = 'data:image/jpeg;base64,' + encoded_image.decode("utf-8")
    except Exception as e:
        print('ERROR - {}'.format(e))
        final_df.at[index, 'image'] = 0
print(final_df.shape)
data_dict = final_df.fillna('').to_dict('r')
return Response(data=data_dict, status=status.HTTP_200_OK)

MultipleObjectsReturned: get() returned more than one ForestOfficial -- it returned 2!

In [10]:
import pandas as pd

industry_df

,industry_office_id,industry_name,street,village,taluk,pincode,block,district,state,is_head_office,image
0,7,Reliance,main,Coimbatore South,Coimbatore South,641015,,Coimbatore,Tamil Nadu,True,

In [18]:
industry_office_obj = IndustryOffice.objects.filter(is_head_office=True)
industry_incharge_obj = IndustryOfficial.objects.all()

industry_value_list = list(industry_office_obj.values_list('id','industry__name', 'street', 'village', 'taluk', 'pincode', 'block', 'district', 'state', 'is_head_office', 'image'))                                                                                                                     
industry_value_column = ['industry_office_id', 'industry_name', 'street', 'village', 'taluk', 'pincode', 'block', 'district', 'state', 'is_head_office', 'image']
industry_df = pd.DataFrame(industry_value_list, columns=industry_value_column)
industry_df = industry_df.fillna('')

incharge_value_list = list(industry_incharge_obj.values_list('id','user_profile_id', 'industry_office_id', 'user_profile__user__first_name', 'user_profile__user__last_name', 'user_profile__mobile', 'is_contact_person', 'user_profile__user__email'))
incharge_value_column = ['industry_incharge_id','user_profile_id', 'industry_office_id', 'first_name', 'last_name', 'mobile', 'contact_person', 'email']
incharge_df = pd.DataFrame(incharge_value_list, columns=incharge_value_column)
incharge_df = incharge_df[incharge_df['contact_person']==True]
incharge_df

final_df = pd.merge(incharge_df, industry_df, left_on='industry_office_id', right_on='industry_office_id', how='left')
final_df = final_df.fillna('')
final_df

for index, row in final_df.iterrows():
    image_path = settings.MEDIA_ROOT + '/' + str(row.image)
    final_df.at[index, 'full_address'] = str(row.street) + ', ' + str(row.village) + ', ' + str(row.taluk) + ', ' + str(row.block) + ', ' + str(row.district) + ', ' + str(row.state) 
    try:
        with open(image_path, 'rb') as image_file:
            encoded_image = b64encode(image_file.read())
            final_df.at[index, 'image'] = 'data:image/jpeg;base64,' + encoded_image.decode("utf-8")
    except Exception as e:
        print('ERROR - {}'.format(e))
        final_df.at[index, 'image'] = 0

ERROR - [Errno 2] No such file or directory: '/home/r_k_vijay/Softwares/jamun/jamun_admin/media/'

,industry_incharge_id,user_profile_id,industry_office_id,first_name,last_name,mobile,contact_person,email,industry_name,street,village,taluk,pincode,block,district,state,is_head_office,image,full_address
0,4,1632,7,Raju,Bai,785658574,True,ruaju@gmail.com,Reliance,main,Coimbatore South,Coimbatore South,641015,,Coimbatore,Tamil Nadu,True,0,"main, Coimbatore South, Coimbatore South, , Co..."

In [2]:
import pandas as pd
forest_office_obj = ForestOffice.objects.filter(is_head_office=True)
forest_incharge_obj = ForestOfficial.objects.all()

forest_value_list = list(forest_office_obj.values_list('id','forest__name', 'street', 'village', 'taluk', 'pincode', 'block', 'district', 'state', 'is_head_office', 'image'))                                                                                                                     
forest_value_column = ['forest_office_id', 'forest_name', 'street', 'village', 'taluk', 'pincode', 'block', 'district', 'state', 'is_head_office', 'image']
forest_df = pd.DataFrame(forest_value_list, columns=forest_value_column)
forest_df = forest_df.fillna('')
forest_df

,forest_office_id,forest_name,street,village,taluk,pincode,block,district,state,is_head_office,image
0,11,Kotagiri,Coimbatore,Coimbatore South,Coimbatore South,641016,,Coimbatore,Tamil Nadu,True,

In [7]:
forest_office_obj = ForestOffice.objects.filter(is_head_office=True)
forest_incharge_obj = ForestOfficial.objects.all()

forest_value_list = list(forest_office_obj.values_list('id','forest__name', 'street', 'village', 'taluk', 'pincode', 'block', 'district', 'state', 'is_head_office', 'image'))                                                                                                                     
forest_value_column = ['forest_office_id', 'forest_name', 'street', 'village', 'taluk', 'pincode', 'block', 'district', 'state', 'is_head_office', 'image']
forest_df = pd.DataFrame(forest_value_list, columns=forest_value_column)
forest_df = forest_df.fillna('')

forest_value_list = list(forest_incharge_obj.values_list('id','user_profile_id', 'forest_office_id', 'user_profile__user__first_name', 'user_profile__user__last_name', 'user_profile__mobile', 'is_contact_person', 'user_profile__user__email'))
forest_officer_value_column = ['forest_official_id','user_profile_id', 'forest_office_id', 'first_name', 'last_name', 'mobile', 'contact_person', 'email']
incharge_df = pd.DataFrame(forest_value_list, columns=forest_officer_value_column)
incharge_df = incharge_df[incharge_df['contact_person']==True]

final_df = pd.merge(forest_df, incharge_df, left_on='forest_office_id', right_on='forest_office_id', how='left')
final_df = final_df.fillna('')

for index, row in final_df.iterrows():
    image_path = settings.MEDIA_ROOT + '/' + str(row.image)
    final_df.at[index, 'full_address'] = str(row.street) + ', ' + str(row.village) + ', ' + str(row.taluk) + ', ' + str(row.block) + ', ' + str(row.district) + ', ' + str(row.state) 
    try:
        with open(image_path, 'rb') as image_file:
            encoded_image = b64encode(image_file.read())
            final_df.at[index, 'image'] = 'data:image/jpeg;base64,' + encoded_image.decode("utf-8")
    except Exception as e:
        print('ERROR - {}'.format(e))
        final_df.at[index, 'image'] = 0
final_df

ERROR - [Errno 2] No such file or directory: '/home/r_k_vijay/Softwares/jamun/jamun_admin/media/'

,forest_office_id,forest_name,street,village,taluk,pincode,block,district,state,is_head_office,image,forest_official_id,user_profile_id,first_name,last_name,mobile,contact_person,email,full_address
0,11,Kotagiri,Coimbatore,Coimbatore South,Coimbatore South,641016,,Coimbatore,Tamil Nadu,True,0,11,1634,ruban,bharath,453545353,True,ciae@gmail.com,"Coimbatore, Coimbatore South, Coimbatore South..."

In [8]:
User.objects.filter(username='8610233729')